# YAML file for LDP 1.0

# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "1.0.0"
  title: LDP API

schemes:
  - http

license: Apache 2.0

# host: <to be inserted here>

consumes:
  - application/rdf+xml
  - application/json+ld

produces:
  - application/rdf+xml
  - application/json+ld

basePath: /containers

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /{containerID}:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Person` objects.
        Optional query param of **size** determines
        size of returned array
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        - name: containerID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64

      # Expected responses for this operation:
      responses:
        # Response code
        "200":
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          headers:
            type:
              description: Target URI matching type of container
              type: string
            Content-Type:
              description: Content-Type for resource
              type: string

          schema:
            $ref: '#/definitions/LDPContainer'
        
        "404":
          description: Unable to find container

        default:
          description: Unsuccessful response
        
     post:
      # adding content type?
      parameters:
        - name: containerID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64
        - name: resource
          in: body
          description: Resource to insert into container
          required: true
          schema:
            $ref: '#/definitions/LDPResource'
        - name: Slug
          in: header
          description: Suggested URI for resource
          required: false
          type: string
        - name: Content-Type
          in: header
          description: Content-Type of resource
          required: false
          type: string

      responses:

        "200":
          description: Successful response

        "201":
          description: Successful creation
          headers:
            Location:
              description: URI to created resource
              type: string
        
        "404":
          description: Unable to find container

        "405":
          description: Method not allowed
          headers:
            Allow:
              description: HTTP methods allowed
              type: array
              items:
                name: Method
                type: string

        "409":
          description: URI Already Exists

        default:
          description: Unsuccessful response

    put:

      parameters:
        - name: containerID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64
        - name: resource
          in: body
          description: Resource to insert into container
          required: true
          schema:
            $ref: '#/definitions/LDPResource'
        - name: Slug
          in: header
          description: Suggested URI for resource
          required: false
          type: string
        - name: Content-Type
          in: header
          description: Content-Type of resource
          required: false
          type: string

      responses:

        "200":
          description: Successful response

        "404":
          description: Unable to find container

        "405":
          description: Method not allowed
          headers:
            Allow:
              description: HTTP methods allowed
              type: array
              items:
                name: Method
                type: string

        "409":
          description: URI Already Exists

        default:
          description: Unsuccessful response

    patch:

      parameters:
        - name: containerID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64
        - name: resource
          in: body
          description: Resource to insert into container
          required: true
          schema:
            $ref: '#/definitions/LDPResource'

      responses:

        "200":
          description: Successful response

        "404":
          description: Unable to find container

        "405":
          description: Method not allowed
          headers:
            Allow:
              description: HTTP methods allowed
              type: array
              items:
                name: Method
                type: string

        "406":
          description: Violates constraints on resource modification
          headers:
            Accept-Patch:
                description: Content that can be modified using the PATCH request
                type: array
                items:
                  name: Content
                  description: Content that can be modified using PATCH
                  type: string

        default:
          description: Unsuccessful response

    delete:

      parameters:
        - name: containerID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64

      responses:

        "200":
          description: Successful response

        "404":
          description: Unable to find container

        "405":
          description: Method not allowed
          headers:
            Allow:
              description: HTTP methods allowed
              type: array
              items:
                name: Method
                type: string

        default:
          description: Unsuccessful response

    options:

      parameters:
        - name: containerID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64

      response:

        "200":
          description: Successful response
          headers:
            Accept:
              description: Lists HTTP methods that can be used on this resource
              type: array
              items:
                name: Method
                description: Allowed HTTP method
                type: string

            Accept-Patch:
              description: Content that can be modified using the PATCH request
              type: array
              items:
                name: Content
                description: Content that can be modified using PATCH
                type: string

        "404":
          description: Unable to find container

        default:
          description: Unsuccessful response

    # What should be returned here??
    head:

      parameters:
        - name: containerID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64

      responses:

        "200":
          description: Successful response
          headers:
            Allow:
              type: array
              items:
               name: Method
                type: string

        "404":
          description: Unable to find container

        default:
          description: Unsuccessful response

  /{containerID}/{resourceID}:

    get:

      parameters:
        - name: containerID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64
        - name: resourceID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64

      responses:

        "200":
          description: Successful response
          headers:
            Allow:
              type: array
              items:
               name: Method
                type: string
            ETag:
              description: ETag for this resource
              type: string
            Content-Type:
              description: Content-Type for resource
              type: string

          schema:
            $ref: '#/definitions/LDPResource'

        "404":
          description: Unable to find resource

        default:
          description: Unsuccessful response

    post:

      parameters:
        - name: containerID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64
        - name: resourceID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64
        - name: resource
          in: body
          description: Resource to create
          required: true
          schema:
            $ref: '#/definitions/LDPResource'
        - name: Content-Type
          in: header
          description: Content-Type of resource
          required: false
          type: string

      responses:

        "200":
          description: Successful response

        "404":
          description: Unable to find resource

        "405":
          description: Method not allowed
          headers:
            Allow:
              description: HTTP methods allowed
              type: array
              items:
                name: Method
                type: string
        default:
          description: Unsuccessful response

    put:

      parameters:
        - name: containerID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64
        - name: resourceID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64
        - name: resource
          in: body
          description: Resource to update or create
          required: true
          schema:
            $ref: '#/definitions/LDPResource'
        - name: Content-Type
          in: header
          description: Content-Type of resource
          required: false
          type: string

      responses:

        "200":
          description: Successful response
          headers:
            ETag:
              description: ETag for this resource
              type: string

        "404":
          description: Unable to find resource

        "405":
          description: Method not allowed
          headers:
            Allow:
              description: HTTP methods allowed
              type: array
              items:
                name: Method
                type: string

        "409":
          description: Property cannot be modified
          schema:
            type: string

        "412":
          description: ETags don't match

        default:
          description: Unsuccessful response

    patch:

      parameters:
        - name: containerID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64
        - name: resourceID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64

      responses:

        "200":
          description: Successful response

        "404":
          description: Unable to find resource

        "405":
          description: Method not allowed
          headers:
            Allow:
              description: HTTP methods allowed
              type: array
              items:
                name: Method
                type: string

        "406":
          description: Violates constraints on resource modification
          headers:
            Accept-Patch:
                description: Content that can be modified using the PATCH request
                type: array
                items:
                  name: Content
                  description: Content that can be modified using PATCH
                  type: string

        default:
          description: Unsuccessful response

    delete:

      parameters:
        - name: containerID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64
        - name: resourceID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64

      responses:

        "200":
          description: Successful response

        "404":
          description: Unable to find resource

        "405":
          description: Method not allowed
          headers:
            Allow:
              description: HTTP methods allowed
              type: array
              items:
                name: Method
                type: string

        default:
          description: Unsuccessful response

    options:

      parameters:
        - name: containerID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64
        - name: resourceID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64

      responses:

        "200":
          description: Successful response
          headers:
            Accept:
              description: Lists HTTP methods that can be used on this resource
              items:
                name: Method
                description: Allowed HTTP method
                type: string

            Accept-Patch:
              description: Content that can be modified using the PATCH request
              type: array
              items:
                name: Content
                description: Content that can be modified using PATCH
                type: string

        "404":
          description: Unable to find resource

        default:
          description: Unsuccessful reponse

    head:

      parameters:
        - name: containerID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64
        - name: resourceID
          in: path
          description: LDP Container to get
          required: true
          type: integer
          format: int64

      resources:

        "200":
          description: Successful response
          headers:
            Allow:
              type: array
              items:
               name: Method
                type: string

        "404":
          description: Unable to find resource

        default:
          description: Unsuccessful response

definitions:

  LDPResource:
    required:
      - resourceID
      - name
      - URI
    properties:
      resourceID:
        type: integer
        format: int64
      name:
        type: string
      URI:
        type: string

  LDPContainer:
    required:
      - containerID
      - name
      - URI
      - resources
    properties:
      containerID:
        type: integer
        format: int64
      name:
        type: string
      URI:
        type: string
      resources:
        type: array
        items:
          $ref: '#/definitions/LDPResource'

